apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cs312-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: cs312.rules
      rules:
        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[5m]) > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} is crash looping"
            runbook: |
              1. Run: kubectl describe pod {{ $labels.pod }} -n {{ $labels.namespace }}
              2. Check Events section for error messages
              3. Check logs: kubectl logs {{ $labels.pod }} --previous
              4. If bad image, rollback: kubectl rollout undo deployment/<name>

        - alert: HighNodeCPU
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Node CPU usage above 80% for 2 minutes"
            runbook: |
              1. Run: kubectl top pods --all-namespaces --sort-by=cpu
              2. Identify the Pod consuming the most CPU
              3. Check if it is expected (build, migration) or unexpected (infinite loop)
              4. If unexpected, check resource limits and consider scaling

        - alert: PodNotReady
          expr: kube_pod_status_ready{namespace="default", condition="true"} == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is not ready"
            runbook: |
              1. Run: kubectl describe pod {{ $labels.pod }} -n {{ $labels.namespace }}
              2. Check readiness probe configuration and recent events
              3. Check logs: kubectl logs {{ $labels.pod }}
              4. If the Pod is failing to start, check image and config
        - alert: MinecraftServiceDown
          expr: kube_pod_status_ready{pod=~"minecraft-.*", condition="true"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Minecraft server is unreachable by players"
            runbook: |
              Determine the source of the issue via one of the following actions
              1. Check pod status: kubectl get pods -l app=minecraft
              2. Check logs: kubectl logs $(kubectl get pods -l app=minecraft -o jsonpath='{.items[0].metadata.name}')
              3. Check for session.lock issue: kubectl describe pod $(kubectl get pods -l app=minecraft -o jsonpath='{.items[0].metadata.name}')
              5. If cause isn't found easily, restart deployment: kubectl rollout restart deployment/minecraft
